insert into webapijwt.cities values (null, 'Funchal', 177);
insert into webapijwt.cities values (null, 'Setúbal', 177);
insert into webapijwt.cities values (null, 'Funchal', 177);
insert into webapijwt.cities values (null, 'Lisbon', 177);
insert into webapijwt.cities values (null, 'Évora', 177);
insert into webapijwt.cities values (null, 'Angra do Heroísmo', 177);
insert into webapijwt.cities values (null, 'Santarém', 177);
insert into webapijwt.cities values (null, 'Horta', 177);
insert into webapijwt.cities values (null, 'Ponta Delgada', 177);
insert into webapijwt.cities values (null, 'Porto', 177);
insert into webapijwt.cities values (null, 'Faro', 177);
insert into webapijwt.cities values (null, 'Vila Real', 177);
insert into webapijwt.cities values (null, 'Aveiro', 177);
insert into webapijwt.cities values (null, 'Guarda', 177);
insert into webapijwt.cities values (null, 'Viseu', 177);
insert into webapijwt.cities values (null, 'Bragança', 177);
insert into webapijwt.cities values (null, 'Viana Do Castelo', 177);
insert into webapijwt.cities values (null, 'Braga', 177);
insert into webapijwt.cities values (null, 'Beja', 177);
insert into webapijwt.cities values (null, 'Castelo Branco', 177);
insert into webapijwt.cities values (null, 'Portalegre', 177);
insert into webapijwt.cities values (null, 'Coimbra', 177);
insert into webapijwt.cities values (null, 'Leiria', 177);
insert into webapijwt.cities values (null, 'Covilhã', 177);
insert into webapijwt.cities values (null, 'Portimão', 177);
